### ISSUE TITLE
Guides should not ‘Edit’ dream to see dream details - show be on the main page view

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#75] opened 2017-01-15 10:57 UTC
Right now to see all of the new fields for the dream - a guide needs to 'Edit' a dream.
Add a new button - 'View' to open the 'Edit' dream just with readonly access - so no fields will be changed

**Comment by sh0oki** [comment] 2017-01-24 22:06
Duplicate of #109, removing

**Closed as completed** 2017-01-24 22:06 UTC
Labels: Feature
