### ISSUE TITLE
Show important dates when editing a dream at the top

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#102] opened 2017-01-18 09:34 UTC
Show the dates with countdown backward - '10 days to bla'. '5 hours to bla bla' - Create somewhere in the app - a place to enter dates with a known dateformat and time and then countback from that time

**Comment by sh0oki** [comment] 2017-01-24 22:17
Duplicate of #83, closing

**Closed as completed by sh0oki** 2017-01-24 22:17 UTC
Labels: Feature
